version: '3'

services:
  app:
    image: php:8.1-fpm-alpine
    build: .
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    logging:
      options:
        max-size: 10m
    networks:
      - app-network

  webserver:
    depends_on:
      - app
      - db
    image: nginx:1.21.4-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - '${HMR_PORT:-5173}:5173'
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dev_database
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
      MYSQL_RANDOM_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']        
    networks:
      - app-network

volumes:
    db_data:
networks:
  app-network:
    driver: bridge        
